# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
    
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'any cpu'
    configuration: 'release'
    clean: true
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
    createLogFile: true
    
- task: WhiteSource Bolt@20
  inputs:
    cwd: 'https://github.com/mohammed-taha11/EasyApp.git'
